trigger:
- install-only

variables:
  adminUser: 'azureuser'
  adminPass: 'Appr0ved!!!!'
  resourceGroup: 'SAP_RG'
  hanaStorageAccountName: 'hanastorageaccount171'
  containerName: 'hana'
  customScriptFileUri: 'https://$(hanaStorageAccountName).blob.core.windows.net/$(containerName)/install-hana-sles3.sh'

pool:
  vmImage: ubuntu-latest
  
jobs:
  - job: deploy_hana
    displayName: 'Deploy Single Instance HANA'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureSAPConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Calling install-hana-sles3.sh to install HANA..."
          echo "Using custom script URI: $(customScriptFileUri)"
          az deployment group create \
            --resource-group $(resourceGroup) \
            --template-file $(Build.SourcesDirectory)/scripts/sip-hana.bicep \
            --parameters adminUsername=$(adminUser) adminPassword=$(adminPass) \
            customScriptFileUri=$(customScriptFileUri) \
            hanaStorageAccountName=$(hanaStorageAccountName) \
            containerName=$(containerName)
