trigger:
- new-bicep-file

variables:
  adminUser: 'azureuser'
  adminPass: 'Appr0ved!!!!'

pool:
  vmImage: ubuntu-latest
  
jobs:
  - job: deploy_hana
    displayName: 'Deploy Single Instance HANA'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureSAPConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group SAP_RG \
            --template-file $(Build.SourcesDirectory)/scripts/sip-hana2.bicep \
            --parameters adminUsername=$(adminUser) adminPassword=$(adminPass)
